### ISSUE TITLE
Remove project root from workspace throws error

### ISSUE THREAD

**Issue by dcalhoun** [sQu1rr/nerd-treeview#18]
Steps to reproduce:

1. Open project in Atom.
2. Open tree view (<kbd>Cmd</kbd>+<kbd>\\</kbd>).
3. Ensure cursor is focused on project root.
5. Remove the project from workspace (<kbd>Shift</kbd>+<kbd>d</kbd>).

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package 0.215.1

### Stack Trace

Uncaught TypeError: ref2.querySelector is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/tree-view/lib/tree-view.js:1211

TypeError: ref2.querySelector is not a function
    at TreeView.module.exports.TreeView.removeProjectFolder (/app.asar/node_modules/tree-view/lib/tree-view.js:1211:98)
    at Object.remove (/packages/nerd-treeview/lib/nerd-treeview.coffee:413:22)
    at /packages/nerd-treeview/lib/nerd-treeview.coffee:96:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
  2x -0:23.8.0 nerd-treeview:open (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  6x -0:22.8.0 nerd-treeview:jump-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:21.6.0 nerd-treeview:open-tree-stay (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  7x -0:20.6.0 nerd-treeview:jump-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:20.1.0 nerd-treeview:move-to-bottom-of-screen (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
 13x -0:20 nerd-treeview:jump-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:17.7.0 nerd-treeview:jump-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:17.1.0 nerd-treeview:jump-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:15.6.0 nerd-treeview:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:12.9.0 nerd-treeview:clear-prefix (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:08.3.0 nerd-treeview:jump-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  2x -0:07.9.0 nerd-treeview:jump-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:07.6.0 nerd-treeview:jump-down (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:06.9.0 nerd-treeview:jump-up (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:06.2.0 nerd-treeview:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:05.6.0 nerd-treeview:clear-prefix (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Non-Core Packages

```
atom-jest-snippets-standard 1.1.0 
busy-signal 1.4.1 
file-icons 2.1.4 
gist-it 0.9.2 
highlight-line 0.12.0 
import-sf-mono 1.0.1 
intentions 1.1.2 
language-diff 0.7.0 
language-generic-config 1.3.0 
language-liquid 0.5.1 
linter 2.1.4 
linter-js-standard 3.9.0 
linter-stylelint 3.10.0 
linter-ui-default 1.2.3 
nerd-treeview 0.5.2 
one-dark-vivid-syntax 1.7.1 
react 0.16.2 
tabs-to-spaces 1.0.3 
vim-mode-plus 0.91.0 
vim-mode-plus-ex-mode 0.9.0 
vim-mode-plus-jasmine-increase-focus 0.3.0 
Zen 0.16.4 
```

**Comment by sQu1rr** [comment]
Will look into it
